#pragma once

#define OPEN_FILE_EXEPTION				0
#define EMPTY_FILE_EXEPTION				1
#define WRONG_BUFFER_STATE_EXEPTION		2
#define READING_FILE_EXEPTION			3
#define WRITING_FILE_EXEPTION			4
#define WRONG_KIND_NUMBERS				5
#define END_OF_FILE_EXEPTION			6
#define ERROR_DELETING_FILE			    7
#define TO_LONG_FILEPATH			    8
#define ERROR_RENAMING_FILE				9